### ISSUE TITLE
Install error: search_api

### ISSUE THREAD

**Issue by GustavoMarcante** [acquia/df-project#3]
Installing Demo Framework (core 8.3.5) using `composer create-project acquia/df-project MY_PROJECT`
I got this error:

    Notice: Undefined index: total in Drupal\search_api\Task\TaskManager->finishBatch() (line 334 of modules/contrib/search_api/src/Task/TaskManager.php).

    Drupal\search_api\Task\TaskManager->finishBatch(1, Array, Array, Object) (Line: 414)
    _batch_finished() (Line: 81)
    _batch_page(Object) (Line: 638)
    install_run_task(Array, Array) (Line: 546)
    install_run_tasks(Array) (Line: 117)
    install_drupal(Object) (Line: 44)

    Notice: Undefined index: total in Drupal\search_api\Task\TaskManager->finishBatch() (line 334 of modules/contrib/search_api/src/Task/TaskManager.php).

    Drupal\search_api\Task\TaskManager->finishBatch(1, Array, Array, Object) (Line: 414)
    _batch_finished() (Line: 81)
    _batch_page(Object) (Line: 638)
    install_run_task(Array, Array) (Line: 546)
    install_run_tasks(Array) (Line: 117)
    install_drupal(Object) (Line: 44)

**Comment by saltednut** [comment]
Hi - I usually install via drush but saw this today via the UI installer.  It seems like an issue with search_api so probably best to file the issue on their queue.  I am not sure this is unique to demo framework.

**Comment by saltednut** [comment]
This should be resolved now.
