### ISSUE TITLE
onelogin/php-saml is requesting ext-mcrypt but it's not compatible OOTB with PHP 7.2

### ISSUE THREAD

**Issue by anavarre** [acquia/df-project#6]
With PHP 7.2, installing the project fails with:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - onelogin/php-saml v2.13.0 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
```

We could have users work around the issue by trying to install `ext-mcrypt` on PHP 7.2 or fix the issue through following the outcome of https://github.com/onelogin/php-saml/issues/255

**Comment by saltednut** [comment]
Yeah you'll need to install that yourself. I have this gist that should help.  https://gist.github.com/brantwynn/8765027ec48eeaec82d11a5573206b4e

**Comment by saltednut** [comment]
I don't see how this is a bug with the df-project itself tbh. This should affect anyone using acquia/df

It should also affect anyone using `drupal/samlauth` so I would take it up with them, not this project.

**Comment by anavarre** [comment]
> I don't see how this is a bug with the df-project itself tbh.

Just raising awareness in case we'd want to pin to the package to a dev version or have a patch in the `composer.json` file.

**Comment by anavarre** [comment]
FWIW it looks like `onelogin/php-saml:3.0.0.x-dev` would do for the time being as per https://github.com/onelogin/php-saml/issues/255#issuecomment-371112810

**Comment by techmatevaibhav** [comment]
What is the actual solution of this issue. i am trying upgrade my laravel version 5.7 and its show me same error. 

**Error** 
  - aacotroneo/laravel-saml2 0.11.1 requires onelogin/php-saml ^2.10 -> satisfiable by onelogin/php-saml[2.10.0, 2.10.1, 2.10.2, 2.10.3, 2.10.4, 2.10.5, 2.10.6, 2.10.7, 2.11.0, v2.12.0, v2.13.0, v2.14.0].
    - onelogin/php-saml v2.14.0 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.

**Comment by saltednut** [comment]
As I said above, you'll need to install mcrypt yourself. Pasted from the gist from https://github.com/acquia/df-project/issues/6#issuecomment-395089781

```brew install libmcrypt```
```pecl install mcrypt-1.0.1```

**Comment by tvlooy** [comment]
there is a reason why mcrypt is no longer in core. Afaik the long term solution should be to switch the code to openssl, instead of dragging in a very questionable extension
